version: "3.8"

services:
  # -------------------- Calibre --------------------
  calibre-web:
    image: lscr.io/linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
        #- DOCKER_MODS=linuxserver/mods:universal-calibre #optional
        #- OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - ./calibre-web/data:/config
      - ./calibre-web/library:/books
    networks:
      - calibre
    restart: unless-stopped

  # -------------------- Fava --------------------
  fava:
    image: yegle/fava
    container_name: fava
    hostname: fava
    environment:
      - BEANCOUNT_FILE=/bean/example.bean
    restart: unless-stopped
    networks:
      - fava
    volumes:
      - ./fava/bean:/bean
    entrypoint: fava --prefix /beancount

  # -------------------- Gitea --------------------
  gitea:
    image: gitea/gitea:1.16.9
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: unless-stopped
    networks:
      - gitea
    ports:
      - 3000:3000
      - 222:22
    volumes:
      - ./gitea:/data
      - ./gitea/app.ini:/etc/gitea/conf/app.ini
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  # -------------------- devdocs --------------------
  devdocs:
    build: ./devdocs
    container_name: devdocs
    restart: unless-stopped
    networks:
      - devdocs
    ports:
      - 9292:9292

  # -------------------- Searx --------------------
  searx:
    build: ./searx
    container_name: searx
    networks:
      - searx
    volumes:
    - ./searx-data:/etc/searx
    ports:
      - 8080:8080
    environment:
      - BASE_URL=http://192.168.1.132:8080

  # -------------------- Postgres --------------------
  postgres:
    image: postgres:14.1-alpine
    restart: unless-stopped
    networks:
      - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg:/var/lib/postgresql/data

  # -------------------- Backlogger --------------------
  backlogger:
    build: ./backlogger/backlogger
    container_name: backlogger
    restart: unless-stopped
    networks:
      - backlogger
      - postgres
    ports:
      - 8081:4000
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=backlogger
      - PGHOST=postgres
      - PGPORT=5432
      - DATABASE_URL=ecto://postgres:postgres@postgres/backlogger
      - SECRET_KEY_BASE=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

  # -------------------- Nginx Gateway --------------------
  nginx:
    depends_on:
      - fava
      - calibre-web
      - gitea
      - devdocs
    image: nginx:alpine
    container_name: nginx-gateway
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/index.html:/var/www/html/index.html
    ports:
      - 80:80
    networks:
      - fava
      - calibre
      - gitea
      - devdocs

networks:
  calibre:
    external: false
  fava:
    external: false
  gitea:
    external: false
  devdocs:
    external: false
  searx:
    external: false
  postgres:
    external: false
  backlogger:
    external: false

volumes:
  pg:
    driver: local
